## cloud.redhat.com account prep

* Create an upload user

## Admin host

* Setup Insights Client

----
yum -y install insights-client
mkdir ~/.config
cd ~/.config
cat insights-client.conf
----

* Add upload user for account to insights config file, BASIC AUTH

./home/USER/.config/insights-client.conf
----
[insights-client]
# Example options in this file are the defaults

# Change log level, valid options DEBUG, INFO, WARNING, ERROR, CRITICAL. Default DEBUG
loglevel=DEBUG

# Log each line executed
#trace=False

# Attempt to auto configure with Satellite server
auto_config=FALSE

# Change authentication method, valid options BASIC, CERT. Default BASIC
authmethod=BASIC

# username to use when authmethod is BASIC
username=insights-upload-rhte19mbu1org
# password to use when authmethod is BASIC
password=yaR3dBRKg2iPkPy

#_insights_username: 'insights-upload-gpte'
#_insights_password: '[2qW/},8"o#x2GG}!64Ab!.'

#base_url=cert-api.access.redhat.com:443/r/insights

# URL for your proxy.  Example: http://user:pass@192.168.100.50:8080
#proxy=

# Automatically update the dynamic configuration
#auto_update=True

# Obfuscate IP addresses
#obfuscate=False

# Obfuscate hostname
#obfuscate_hostname=False

# Disallow Insights from creating cron job
#no_schedule=False

# Display name for registration
#display_name=
----

* Test insights upload?

WARNING: might have python ssl dependency issues


* Setup OCP client

----
mkdir ~/bin
cd ~/bin
wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.1.9/openshift-client-linux-4.1.9.tar.gz
tar xzff *
----

* Setup Korekuta

** Get the bits

----
yum -y install unzip

## cloud.redhat.com account prep

* Create an upload user

## Admin host

* Setup Insights Client

----
yum -y install insights-client
mkdir ~/.config
cd ~/.config
cat insights-client.conf
----

* Add upload user for account to insights config file, BASIC AUTH

./home/USER/.config/insights-client.conf
----
[insights-client]
# Example options in this file are the defaults

# Change log level, valid options DEBUG, INFO, WARNING, ERROR, CRITICAL. Default DEBUG
loglevel=DEBUG

# Log each line executed
#trace=False

# Attempt to auto configure with Satellite server
auto_config=FALSE

# Change authentication method, valid options BASIC, CERT. Default BASIC
authmethod=BASIC

# username to use when authmethod is BASIC
username=insights-upload-rhte19mbu1org
# password to use when authmethod is BASIC
password=yaR3dBRKg2iPkPy

#_insights_username: 'insights-upload-gpte'
#_insights_password: '[2qW/},8"o#x2GG}!64Ab!.'

#base_url=cert-api.access.redhat.com:443/r/insights

# URL for your proxy.  Example: http://user:pass@192.168.100.50:8080
#proxy=

# Automatically update the dynamic configuration
#auto_update=True

# Obfuscate IP addresses
#obfuscate=False

# Obfuscate hostname
#obfuscate_hostname=False

# Disallow Insights from creating cron job
#no_schedule=False

# Display name for registration
#display_name=
----

* Test insights upload?

WARNING: might have python ssl dependency issues


* Setup OCP client

----
mkdir ~/bin
cd ~/bin
wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.1.9/openshift-client-linux-4.1.9.tar.gz
tar xzff *
----

* Setup Korekuta

** Get the bits

----
yum -y install unzip
curl -LOk https://github.com/project-koku/korekuta/archive/master.zip
unzip master.zip
cd korekuta-master
----
curl -LOk https://github.com/project-koku/korekuta/archive/master.zip
unzip master.zip
cd korekuta-master
----
